/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new customer account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and get JWT token */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders (customers see only their own) */
        get: operations["OrderController_listOrders"];
        put?: never;
        /** Create a new order */
        post: operations["OrderController_createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an order by ID */
        get: operations["OrderController_getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subscribe to real-time order status events (SSE) */
        get: operations["OrderController_orderEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an order */
        post: operations["OrderController_confirmOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an order */
        post: operations["OrderController_cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process a payment */
        post: operations["PaymentController_processPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get payment by ID */
        get: operations["PaymentController_getPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refund a payment */
        post: operations["PaymentController_refundPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all inventory items (paginated) */
        get: operations["InventoryController_listInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/sku/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get inventory item by SKU */
        get: operations["InventoryController_getInventoryBySku"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get inventory item by ID */
        get: operations["InventoryController_getInventoryById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve inventory for an order */
        post: operations["InventoryController_reserveInventory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release inventory reservation */
        post: operations["InventoryController_releaseInventory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a shipment */
        post: operations["ShippingController_createShipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get shipment by ID */
        get: operations["ShippingController_getShipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update shipment status */
        patch: operations["ShippingController_updateShipmentStatus"];
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get notifications by recipient */
        get: operations["NotificationController_getNotifications"];
        put?: never;
        /** Send a notification */
        post: operations["NotificationController_sendNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard overview metrics and widgets */
        get: operations["DashboardController_getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dashboard orders */
        get: operations["DashboardController_listOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get detailed dashboard order view */
        get: operations["DashboardController_getOrderDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List inventory for the dashboard */
        get: operations["DashboardController_listInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payments for the dashboard */
        get: operations["DashboardController_listPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List shipments for the dashboard */
        get: operations["DashboardController_listShipments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notifications for the dashboard */
        get: operations["DashboardController_listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get normalized dashboard infrastructure health */
        get: operations["DashboardController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recent cross-system activity feed */
        get: operations["DashboardController_getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /**
             * @description User ID (min 3 chars)
             * @example user-123
             */
            userId: string;
            /**
             * @description Email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description Full name
             * @example John Doe
             */
            name: string;
            /**
             * @description Password (min 8 chars)
             * @example securepassword
             */
            password: string;
        };
        LoginRequest: {
            /**
             * @description User ID
             * @example user-123
             */
            userId: string;
            /**
             * @description User role
             * @example customer
             * @enum {string}
             */
            role: "admin" | "customer" | "service";
            /**
             * @description Password (required for customer role)
             * @example securepassword
             */
            password?: string;
        };
        CreateOrderRequest: Record<string, never>;
        OrderItemResponseDto: {
            id: string;
            productId: string;
            productName: string;
            quantity: number;
            unitPrice: number;
            totalPrice: number;
            currency: string;
        };
        OrderShippingAddressDto: {
            street: string;
            city: string;
            state: string;
            zipCode: string;
            country: string;
        };
        OrderResponseDto: {
            id: string;
            customerId: string;
            status: string;
            items: components["schemas"]["OrderItemResponseDto"][];
            totalAmount: number;
            currency: string;
            shippingAddress: components["schemas"]["OrderShippingAddressDto"];
            /** Format: date-time */
            createdAt: string;
        };
        ProcessPaymentRequest: Record<string, never>;
        PaymentResponseDto: {
            id: string;
            orderId: string;
            amount: number;
            currency: string;
            status: string;
            transactionId?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        InventoryResponseDto: {
            id: string;
            sku: string;
            productName: string;
            totalQuantity: number;
            reservedQuantity: number;
            availableQuantity: number;
            unitPrice: number;
        };
        ReserveInventoryRequest: Record<string, never>;
        ReleaseInventoryRequest: Record<string, never>;
        CreateShipmentRequest: Record<string, never>;
        ShipmentResponseDto: {
            id: string;
            orderId: string;
            status: string;
            trackingNumber?: Record<string, never> | null;
            carrier?: Record<string, never> | null;
            estimatedDelivery?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateShipmentStatusRequest: Record<string, never>;
        SendNotificationRequest: Record<string, never>;
        NotificationResponseDto: {
            id: string;
            recipientId: string;
            channel: string;
            type: string;
            status: string;
            subject: string;
            body: string;
            failureReason?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardSummaryDto: {
            totalOrders: number;
            ordersToday: number;
            activeOrders: number;
            totalRevenue: number;
            totalInventoryUnits: number;
            lowStockItems: number;
            pendingNotifications: number;
            unhealthyServices: number;
        };
        DashboardStatusCountDto: {
            status: string;
            count: number;
        };
        DashboardTrendPointDto: {
            date: string;
            orders: number;
            revenue: number;
        };
        DashboardInventoryAlertDto: {
            id: string;
            sku: string;
            productName: string;
            availableQuantity: number;
            totalQuantity: number;
            reservedQuantity: number;
            lowStockThreshold: number;
        };
        DashboardRecentOrderDto: {
            id: string;
            customerId: string;
            status: string;
            totalAmount: number;
            currency: string;
            itemCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardActivityDto: {
            /** @enum {string} */
            type: "order" | "payment" | "shipment" | "notification";
            entityId: string;
            title: string;
            description: string;
            status: string;
            /** Format: date-time */
            timestamp: string;
        };
        DashboardHealthServiceDto: {
            name: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "down";
            responseTimeMs?: Record<string, never> | null;
            details: string;
            /** Format: date-time */
            checkedAt: string;
        };
        DashboardHealthResponseDto: {
            /** @enum {string} */
            overallStatus: "healthy" | "degraded" | "down";
            services: components["schemas"]["DashboardHealthServiceDto"][];
            /** Format: date-time */
            generatedAt: string;
        };
        DashboardOverviewResponseDto: {
            summary: components["schemas"]["DashboardSummaryDto"];
            orderStatusDistribution: components["schemas"]["DashboardStatusCountDto"][];
            paymentStatusDistribution: components["schemas"]["DashboardStatusCountDto"][];
            shipmentStatusDistribution: components["schemas"]["DashboardStatusCountDto"][];
            notificationStatusDistribution: components["schemas"]["DashboardStatusCountDto"][];
            orderTrend: components["schemas"]["DashboardTrendPointDto"][];
            lowStockItems: components["schemas"]["DashboardInventoryAlertDto"][];
            recentOrders: components["schemas"]["DashboardRecentOrderDto"][];
            recentActivity: components["schemas"]["DashboardActivityDto"][];
            health: components["schemas"]["DashboardHealthResponseDto"];
            /** Format: date-time */
            generatedAt: string;
        };
        DashboardOrderListItemDto: {
            id: string;
            customerId: string;
            status: string;
            totalAmount: number;
            currency: string;
            itemCount: number;
            shippingAddress: string;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardPaginationDto: {
            total: number;
            limit: number;
        };
        DashboardOrderListResponseDto: {
            data: components["schemas"]["DashboardOrderListItemDto"][];
            meta: components["schemas"]["DashboardPaginationDto"];
        };
        DashboardOrderDetailItemDto: {
            id: string;
            productId: string;
            productName: string;
            quantity: number;
            unitPrice: number;
            currency: string;
            totalPrice: number;
        };
        DashboardPaymentReferenceDto: {
            id: string;
            orderId: string;
            amount: number;
            currency: string;
            status: string;
            method: string;
            transactionId?: Record<string, never> | null;
            failureReason?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardShipmentReferenceDto: {
            id: string;
            orderId: string;
            status: string;
            trackingNumber?: Record<string, never> | null;
            carrierName?: Record<string, never> | null;
            estimatedDelivery?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardOrderDetailDto: {
            id: string;
            customerId: string;
            status: string;
            totalAmount: number;
            currency: string;
            shippingAddress: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            items: components["schemas"]["DashboardOrderDetailItemDto"][];
            payment?: components["schemas"]["DashboardPaymentReferenceDto"] | null;
            shipment?: components["schemas"]["DashboardShipmentReferenceDto"] | null;
        };
        DashboardInventoryListItemDto: {
            id: string;
            sku: string;
            productName: string;
            totalQuantity: number;
            reservedQuantity: number;
            availableQuantity: number;
            lowStockThreshold: number;
            /** @enum {string} */
            stockState: "healthy" | "low" | "critical";
        };
        DashboardInventoryListResponseDto: {
            data: components["schemas"]["DashboardInventoryListItemDto"][];
            meta: components["schemas"]["DashboardPaginationDto"];
        };
        DashboardPaymentListItemDto: {
            id: string;
            orderId: string;
            amount: number;
            currency: string;
            status: string;
            method: string;
            transactionId?: Record<string, never> | null;
            failureReason?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardPaymentListResponseDto: {
            data: components["schemas"]["DashboardPaymentListItemDto"][];
            meta: components["schemas"]["DashboardPaginationDto"];
        };
        DashboardShipmentListItemDto: {
            id: string;
            orderId: string;
            status: string;
            trackingNumber?: Record<string, never> | null;
            carrierName?: Record<string, never> | null;
            estimatedDelivery?: Record<string, never> | null;
            shippingAddress: string;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardShipmentListResponseDto: {
            data: components["schemas"]["DashboardShipmentListItemDto"][];
            meta: components["schemas"]["DashboardPaginationDto"];
        };
        DashboardNotificationListItemDto: {
            id: string;
            recipientId: string;
            channel: string;
            type: string;
            status: string;
            subject: string;
            body: string;
            failureReason?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardNotificationListResponseDto: {
            data: components["schemas"]["DashboardNotificationListItemDto"][];
            meta: components["schemas"]["DashboardPaginationDto"];
        };
        DashboardActivityResponseDto: {
            data: components["schemas"]["DashboardActivityDto"][];
            meta: components["schemas"]["DashboardPaginationDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Customer registered and JWT returned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UserId already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description JWT token returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    HealthController_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    HealthController_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    OrderController_listOrders: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: string;
                /** @description Page size */
                limit?: string;
                /** @description Page number */
                page?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders list returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Order created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_orderEvents: {
        parameters: {
            query: {
                /** @description JWT bearer token (EventSource cannot send headers) */
                token: string;
            };
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of order status events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_confirmOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden: customers can only cancel their own orders */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentController_processPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessPaymentRequest"];
            };
        };
        responses: {
            /** @description Payment processed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponseDto"];
                };
            };
        };
    };
    PaymentController_getPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Payment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponseDto"];
                };
            };
        };
    };
    PaymentController_refundPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Payment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refund initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_listInventory: {
        parameters: {
            query?: {
                /** @description Page size */
                limit?: string;
                /** @description Page number */
                page?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inventory items list returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_getInventoryBySku: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product SKU */
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inventory item retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryResponseDto"];
                };
            };
        };
    };
    InventoryController_getInventoryById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Inventory item ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inventory item retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryResponseDto"];
                };
            };
        };
    };
    InventoryController_reserveInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveInventoryRequest"];
            };
        };
        responses: {
            /** @description Inventory reserved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_releaseInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseInventoryRequest"];
            };
        };
        responses: {
            /** @description Inventory released */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShippingController_createShipment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShipmentRequest"];
            };
        };
        responses: {
            /** @description Shipment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentResponseDto"];
                };
            };
        };
    };
    ShippingController_getShipment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shipment retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentResponseDto"];
                };
            };
        };
    };
    ShippingController_updateShipmentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShipmentStatusRequest"];
            };
        };
        responses: {
            /** @description Status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_getNotifications: {
        parameters: {
            query?: {
                /** @description Recipient ID (admin only; customers always see their own) */
                recipientId?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponseDto"][];
                };
            };
        };
    };
    NotificationController_sendNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendNotificationRequest"];
            };
        };
        responses: {
            /** @description Notification sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponseDto"];
                };
            };
        };
    };
    DashboardController_getOverview: {
        parameters: {
            query: {
                limit: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverviewResponseDto"];
                };
            };
        };
    };
    DashboardController_listOrders: {
        parameters: {
            query?: {
                q?: string;
                status?: string;
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOrderListResponseDto"];
                };
            };
        };
    };
    DashboardController_getOrderDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOrderDetailDto"];
                };
            };
        };
    };
    DashboardController_listInventory: {
        parameters: {
            query: {
                q: string;
                lowStockOnly: string;
                limit: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardInventoryListResponseDto"];
                };
            };
        };
    };
    DashboardController_listPayments: {
        parameters: {
            query: {
                q: string;
                status: string;
                limit: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardPaymentListResponseDto"];
                };
            };
        };
    };
    DashboardController_listShipments: {
        parameters: {
            query: {
                q: string;
                status: string;
                limit: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardShipmentListResponseDto"];
                };
            };
        };
    };
    DashboardController_listNotifications: {
        parameters: {
            query: {
                q: string;
                status: string;
                channel: string;
                limit: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardNotificationListResponseDto"];
                };
            };
        };
    };
    DashboardController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardHealthResponseDto"];
                };
            };
        };
    };
    DashboardController_getActivity: {
        parameters: {
            query: {
                limit: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardActivityResponseDto"];
                };
            };
        };
    };
}
